name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: jdk
          cache: 'gradle'

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@main
