name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: jdk
          cache: 'gradle'

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
